name: public_ip_address
description: This package allows you to get your public IP Address and many others info about it.
version: 1.0.0
homepage: https://github.com/devsumanrazz/IP-Address

environment:
  sdk: '>=2.19.0 <4.0.0'


dependencies:
  http: ^1.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
